name: Build page

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Compile page
        run: |
          yarn
          yarn build
      - uses: actions/upload-artifact@v4
        with:
          path: dist
          if-no-files-found: error
